const cards = [
  {
    keyword: 'Природа',
    title: 'Природа – что такое природа',
    text: 'Понятие «природа» появилось во времена Древней Руси. Корень слова «род», перед которым стоит приставка «при-».',
    date: '19 декабря 2019',
    source: 'Яндекс',
    link: 'https://yandex.ru/turbo/kipmu.ru/s/priroda/',
    image: 'https://avatars.mds.yandex.net/get-turbo/2399174/rthc165f41dec4dfbd16686699af1534c2f/max_g480_c12_r4x3_pd10',
  },
  {
    keyword: 'Природа',
    title: 'Карелия',
    text: 'Карелия, заповедный край лесов и озер, расположилась в северо-западной части России.',
    date: '2 августа, 2019',
    source: 'Wikiway',
    link: 'https://wikiway.com/russia/kareliya/',
    image: 'https://wikiway.com/upload/resize_cache/hl-photo/92b/720_400_1/karelia_128.jpg',
  },
  {
    keyword: 'Природа',
    title: 'Природа – что такое природа',
    text: 'Понятие «природа» появилось во времена Древней Руси. Корень слова «род», перед которым стоит приставка «при-».',
    date: '19 декабря 2019',
    source: 'Яндекс',
    link: 'https://yandex.ru/turbo/kipmu.ru/s/priroda/',
    image: 'https://avatars.mds.yandex.net/get-turbo/2399174/rthc165f41dec4dfbd16686699af1534c2f/max_g480_c12_r4x3_pd10',
  },
  {
    keyword: 'Природа',
    title: 'Карелия',
    text: 'Карелия, заповедный край лесов и озер, расположилась в северо-западной части России.',
    date: '2 августа, 2019',
    source: 'Wikiway',
    link: 'https://wikiway.com/russia/kareliya/',
    image: 'https://wikiway.com/upload/resize_cache/hl-photo/92b/720_400_1/karelia_128.jpg',
  },
  {
    keyword: 'Тайга',
    title: 'Зона тайги. История термина',
    text: 'Слово «тайга» не имеет единой этимологии. Одни источники утверждают, что оно появилось из алтайских языков: тюркского, монгольского и означает – «скалистые горы»',
    date: '2 августа, 2019',
    source: 'Touristam.com',
    link: 'https://touristam.com/tayga-rossii-foto.html',
    image: 'https://touristam.com/wp-content/uploads/2019/04/tayga-rossii-foto-2.jpg',
  },
  {
    keyword: 'Парки',
    title: 'Зеленогорский парк культуры и отдыха',
    text: 'Санкт-Петербургское государственное бюджетное учреждение культуры «Зеленогорский парк культуры и отдыха» находится в городе Зеленогорске, который является частью Курортного района Санкт-Петербурга, расположен в 60 км от него на берегу Финского залива, в живописном уголке Карельского перешейка.',
    date: '2 августа, 2019',
    source: 'Culture.ru',
    link: 'https://www.culture.ru/institutes/35495/zelenogorskii-park-kultury-i-otdykha',
    image: 'https://www.culture.ru/storage/images/b63ccbb8ae037234fbace48691d5cf77/24c866f29bb5a4b8ec9f62f661ac49ae.JPG/c_fill,g_center,w_400,h_292/07cc10a414eaeccc63c8208ed6d9f0a8.jpg',
  },
  {
    keyword: 'Фотография',
    title: 'История фотографии кратко и понятно',
    text: 'Самой первой фотографией считается изображение, созданное в 1826 году французским изобретателем Нисефором Ньепсом.',
    date: '2 августа, 2019',
    source: 'Mofoto',
    link: 'https://mofoto.ru/2020/02/15/istoriya-photografii-kratko/',
    image: 'https://mofoto.ru/wp-content/uploads/2020/02/istoriya-photografii-kratko-moscow-1024x899.jpg',
  },
];

export { cards as default };
